export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST';
export const EDIT_TASK_REQUEST_CANCEL = 'EDIT_TASK_REQUEST_CANCEL';
export const EDIT_TASK_REQUEST_LAST_ACTIVE_INDEX = 'EDIT_TASK_REQUEST_LAST_ACTIVE_INDEX';
